### ISSUE TITLE
About the timing of releasing implementation codes

### ISSUE THREAD

**Issue by simon-zy** [wjun0830/CGDETR#1]
Hi Guys,
First, thx for uploading this awesome paper and make your code opensource on github.
Could you tell more about the releasing timing of the implementation codes, like do you have any plan when to upload it?
I'd appreciate it if you could give a more specific date, thx.

**Comment by wjun0830** [comment]
Hello. Thank you for your interest in our work.
Currently, as we are under our workloads, we are planning to clean our codes during the next one or two weeks.
Thank you for your patience.

**Comment by wjun0830** [comment]
Hello. Simon.
I just have uploaded the implementations.

If there are any issues, please come back to the issue.

Thank you.
