### ISSUE TITLE
Customized dataset feature extraction in Charades-STA style

### ISSUE THREAD

**Issue by xijun-cs** [wjun0830/CGDETR#10]
Hi,

Thanks for your awesome work!

I wanna try your method on a customized dataset, which is similar to Charades-STA.

How can I extract the Slowfast + CLIP feature and the text feature on my own?

Best

**Comment by wjun0830** [comment]
Hello.

Thank you for your interest in our work.
For feature extraction, we suggest you to take a look at Official github repo for CLIP and Slowfast!

Thanks

**Comment by xijun-cs** [comment]
Thanks for your reply.

For double-check, is the clip model ViT-B/32 and slow-fast model SLOWFAST_8x8_R50?

Thanks

**Comment by ArlixLin** [comment]
> Thanks for your reply.
> 
> For double-check, is the clip model ViT-B/32 and slow-fast model SLOWFAST_8x8_R50?
> 
> Thanks

I want to know it too~

**Comment by wjun0830** [comment]
You might want to check out issue https://github.com/jayleicn/moment_detr/issues/19

**Comment by wjun0830** [comment]
And for the clip model yes we used clip b 32 model

**Comment by ArlixLin** [comment]
Thanks, I found my way (ORZ): Your job ->Umt->Moment-DETR->HERO_Video_Feature_Extractor

**Comment by tiesanguaixia** [comment]
> And for the clip model yes we used clip b 32 model

Hi, the visual and text encoder are frozen, just use the offline features, right? Thank you!

**Comment by wjun0830** [comment]
> > And for the clip model yes we used clip b 32 model
> 
> Hi, the visual and text encoder are frozen, just use the offline features, right? Thank you!

Yes you are right
