### ISSUE TITLE
The result on moment retrieval datasets TACoS is from val datasets or test dataset?

### ISSUE THREAD

**Issue by snailma0229** [wjun0830/CGDETR#11]
hi,
thanks for your excellent work!
The result on moment retrieval datasets TACoS is from val datasets or test dataset? This is not stated in the paper.

**Comment by wjun0830** [comment]
Hello. Thanks for your interest in our paper.
We apologize for the inconvenience.
Actually, it is our mistake to report the results for the validation set.
Performances for the test set are as below. Will be updated in the paper.
We again apologize for the inconvenience. Thank you.

|  | R@0.3 | R@0.5 | R@0.7 | mIoU |
| ------- | --------| --------| -----|---- |
| Val set| 52.23 | 39.61 | 22.23 | 36.48|
| Test set |  54.36 | 39.47 | 23.44 | 37.42 |
