### ISSUE TITLE
About Model Zoo

### ISSUE THREAD

**Issue by HTD1016** [wjun0830/CGDETR#13]
![image](https://github.com/user-attachments/assets/90cee92f-338c-48a7-8f47-0b6ed7912e69)
Hi, thanks for providing the code of your work. I wonder what does "only CLIP" means in the Model Zoo. Is it CLIP for the text feature extractor? But what for video feature extractor?

**Comment by wjun0830** [comment]
Hi. thank you for your interest.

Checkpoint "only CLIP" is for the fast demo of our work using the CLIP backbone for both video and text. 
You can check the details in standalone_eval/README.md.

**Comment by HTD1016** [comment]
> Hi. thank you for your interest.
> 
> Checkpoint "only CLIP" is for the fast demo of our work using the CLIP backbone for both video and text. You can check the details in standalone_eval/README.md.

Got it, thanks!
