### ISSUE TITLE
Youtube-HL

### ISSUE THREAD

**Issue by Dokholyan** [wjun0830/CGDETR#17]
Thank you very much for your work. I have a question about the Youtube-HL dataset. I see you in split(https://github.com/wjun0830/CGDETR/blob/main/data/youtube_uni/youtube_splits.py ) videos that are currently unavailable. I would like to know how you got them to extract the signs from the video.

**Comment by wjun0830** [comment]
Hello. Thanks for your interest.

I am not exactly sure since it was long ago.
Maybe it was downloaded from [UMT](https://github.com/TencentARC/UMT?tab=readme-ov-file).
