### ISSUE TITLE
Provided Checkpoint error

### ISSUE THREAD

**Issue by uday-me** [wjun0830/CGDETR#18]
I am running the run.py file using the model checkpoint provided, but get the following error :     magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

On inspecting the checkpoint file , it appears that the file is pointing towards the actual checkpoint stored on Git LFS, however I am unable to pull the weights from there as well. If you could please suggest an alternative way for running the inference code on my custom videos and queries.

**Comment by wjun0830** [comment]
If you are looking for the model trained only with CLIP features for custom video inference, please refer to readme file for checkpoint link, the last row
