### ISSUE TITLE
About the paper

### ISSUE THREAD

**Issue by EdenGabriel** [wjun0830/CGDETR#2]
Hi,
    Thank you for your interesting work. 
    I've read your paper and have some doubts about some details in it. In Fig. 4.(a), how are the positive and negative samples of each clip in the video distinguished during training? Is this process based on GT labels? If so, what happens during inference when there are no GT labels?
   Thanks.

![image](https://github.com/wjun0830/CGDETR/assets/39000840/32800ed1-12df-4ec7-8fda-a9439f01eb35)

**Comment by wjun0830** [comment]
Hello Eden!
First of all, thank you for your interest in our work.

Yes, you are right that positives and negatives are distinguished with the ground-truth labels.

However, as the higher-level aligned space is only needed to infer the fine-grained relationship (clip-word) that is utilized to train the attention weights, we do not use the clip-word correlation learner during the inference.

You can find this detail in our main figure (Fig. 2) that the lines linked to the clip-word correlation learner are dotted and also the contour of the box which denotes only used in training.

If have more questions, please feel free.
Thank you.

![image](https://github.com/wjun0830/CGDETR/assets/31557552/c8326d7e-2c45-49ab-964c-11ac7c19ec69)

**Comment by EdenGabriel** [comment]
Thank you for replying so quickly.

Ah, I was careless, I get it. By the way, can I understand Clip-Word Correlation Learner as an auxiliary strategy to better learn dummy tokens?

Thank you.

**Comment by wjun0830** [comment]
Dummy tokens are mostly supervised with the saliency scores.
Although the clip-word correlation learner may provide further training guidance to learn the dummy tokens, its main objective is to calibrate the attention between each clip and word.
Thank you

**Comment by EdenGabriel** [comment]
OK. I see. Thank you.
Best wishes to you.
