### ISSUE TITLE
QVHIGHLIGHTS Test set

### ISSUE THREAD

**Issue by Dokholyan** [wjun0830/CGDETR#20]
Thank you very much for your work. I have a question: I made some modifications and would like to evaluate the quality on the QVHIGHLIGHTS test set. I tried to submit my results to https://codalab.lisn.upsaclay.fr/competitions/6937#participate, but my submission is still pending. Could you please let me know how long you had to wait for approval to test your model, or is there another way to do it?

**Comment by wjun0830** [comment]
Sorry for late reply
you may better ask the author of momebt detr as they manage those servers!
