### ISSUE TITLE
你好，感谢您的工作，根据您开源的代码程序和数据，我进行了复现，qvhighlights训练的val ，有些指标还是差异比较大的

### ISSUE THREAD

**Issue by yhl2018** [wjun0830/CGDETR#3]
我看到对应的结果里面，您放了results/qvhighlights/model.py  模型文件，是外面的和这个不同导致的结果吗？还是因为什么

 "MR-full-R1@0.3": 76.97,
        **"MR-full-R1@0.5": 65.55,
        "MR-full-R1@0.7": 50.39,
        "MR-full-mAP": 44.66,
        "MR-full-mAP@0.5": 65.49,
        "MR-full-mAP@0.75": 44.82,**
        "MR-full-mIoU": 60.56,
        "MR-long-mAP": 50.2,
        "MR-middle-mAP": 47.1,
        "MR-short-mAP": 11.34,
        "HL-min-Fair-mAP": 77.07,
        "HL-min-Fair-Hit1": 78.77,
        "HL-min-Good-mAP": 65.81,
        "HL-min-Good-Hit1": 76.9,
        "HL-min-VeryGood-mAP": 40.24,
        "HL-min-VeryGood-Hit1": 65.1

**Comment by wjun0830** [comment]
Hello. Thanks for your interest in our work.

Based on our empirical findings we have also observed in our previous work 'QD-DETR' (CVPR23), we think that the gap exists depending on the machine you use and other dependencies including the cuda version.

Also, we observe that performance changes a bit after the code cleaning process  (Even when we did not change any critical details that are used in training). 
Although we are not quite sure about why such an issue happens, we expect the performance may decrease for some while it may increase for others.

Sorry for being not able to clearly solve the issue.

**Comment by yhl2018** [comment]
![1702887963727](https://github.com/wjun0830/CGDETR/assets/36877347/bff9ed38-b4c7-471f-90d8-1cfc05400ea6)

Thank you for your reply. May I ask what is the configuration of the machine used to obtain this experimental parameter? Such as GPU model, python version, torch version, etc

**Comment by wjun0830** [comment]
For that experiment, our versions are
GPU : NVIDIA TITAN RTX
CUDA Version : 11.4
Driver Version : 470.141.03
python 3.7.4

below are the dependencies when we check with "pip freeze"
```
absl-py==0.13.0
asn1crypto==1.2.0
av==8.0.3
backcall==0.1.0
beautifulsoup4==4.8.2
cachetools==4.2.2
certifi==2019.11.28
cffi==1.13.0
chardet==3.0.4
conda==4.8.1
conda-build==3.18.11
conda-package-handling==1.6.0
cryptography==2.8
cycler==0.10.0
dataclasses==0.6
decorator==4.4.1
docopt==0.6.2
ffmpeg==1.4
filelock==3.0.12
future==0.18.2
glob2==0.7
google-auth==1.34.0
google-auth-oauthlib==0.4.5
grpcio==1.39.0
idna==2.8
imageio==2.9.0
importlib-metadata==4.6.3
ipython==7.11.1
ipython-genutils==0.2.0
jedi==0.15.2
Jinja2==2.10.3
joblib==1.0.1
kiwisolver==1.3.1
libarchive-c==2.8
lief==0.9.0
Markdown==3.3.4
MarkupSafe==1.1.1
matplotlib==3.4.2
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
numpy==1.17.4
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
oauthlib==3.1.1
olefile==0.46
opencv-contrib-python==4.5.3.56
opencv-python==4.5.1.48
pandas==1.3.1
parso==0.5.2
pexpect==4.7.0
pickleshare==0.7.5
Pillow==7.0.0
pkginfo==1.5.0.1
prompt-toolkit==3.0.2
protobuf==3.15.6
psutil==5.6.7
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycosat==0.6.3
pycparser==2.19
Pygments==2.5.2
pyOpenSSL==19.0.0
pyparsing==2.4.7
PySocks==1.7.1
python-dateutil==2.8.2
pytz==2019.3
PyYAML==5.2
requests==2.22.0
requests-oauthlib==1.3.0
rsa==4.7.2
ruamel-yaml==0.15.46
scikit-learn==0.24.2
scikit-video==1.1.11
scipy==1.7.1
six==1.12.0
soupsieve==1.9.5
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorboardX==2.1
threadpoolctl==2.2.0
torch==1.13.1
torchtext==0.14.1
torchvision==0.10.0
tqdm==4.36.1
traitlets==4.3.3
typing-extensions==3.10.0.0
urllib3==1.24.2
wcwidth==0.1.7
Werkzeug==2.0.1
zipp==3.5.0
```
