### ISSUE TITLE
Unable to reproduce the experimental results in your paper

### ISSUE THREAD

**Issue by fletcherjiang** [wjun0830/CGDETR#7]
According to your source code, I can't reproduce the results of your model on this dataset on QV-Highlights, there is a big difference, which is far away from your results in your paper, and I have experimented on different graphics cards (3090,2080ti) and none of them can reproduce it, I would like to ask you if you CG-DETR on QV-Highlights this dataset with weakly supervised pretraining with ASR captions for the original 2021 paper? (Not referring to the pre-training on Ego4D and VideoCCdatasets).

Thanks for reading and I hope to get your help soon!

**Comment by wjun0830** [comment]
Hello jiang!

Thanks for your interest.

First of all, we haven't conducted experiments with ASR caption pertaining.

The difference in performances is one thing that we still couldn't find out why it happens in other machine settings.
But, we think that you might be able to obtain the results with minimal parameter tuning. (As we haven't tried to search the learning parameters except for num_dummies, num_prompts, and total_prompts and we know these parameters affect such performance gaps, we recommend you modify these first.)

**Comment by fletcherjiang** [comment]
> Hello jiang!
> 
> Thanks for your interest.
> 
> First of all, we haven't conducted experiments with ASR caption pertaining.
> 
> The difference in performances is one thing that we still couldn't find out why it happens in other machine settings. But, we think that you might be able to obtain the results with minimal parameter tuning. (As we haven't tried to search the learning parameters except for num_dummies, num_prompts, and total_prompts and we know these parameters affect such performance gaps, we recommend you modify these first.)

Could you mind to send me your config file so I can experiment with your parameters? Thank you very much for your reply.

**Comment by wjun0830** [comment]
The configuration for the experiment is saved in the results directory.

https://github.com/wjun0830/CGDETR/blob/main/results/qvhighlights/opt.json

For more details for other datasets, you will be able to find each one with pretrained weights.
